services:
  - type: web
    name: proun-multiplayer-server
    env: node
    buildCommand: npm install
    startCommand: node packages/server/src/index.js
    envVars:
      - key: PORT
        value: 10000
